# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee76b7e76a08ae99971f45dba598d22c9c76c6bff5f482ae3be5756a597efe7540506f6307cf31183f266900a87744d2bcae2ef8ce703fc3215f7f3fe36c9731

test:
  secret_key_base: c93d55b5a9556c1759f7b8e6bc43f6ac8c29d8503041e8982759c43a483c8434e4c105a626568a29037ee8b3bc7ce7e572214d55ab75b4198cb7ff651c05e845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
